### ISSUE TITLE
too many indics 

### ISSUE THREAD

**Issue by Cmnotjx** [THU-DA-6D-Pose-Group/Self6D-Diff-Renderer#11]
Do U have the problem that  : too many indics in tensor of DIM 1???/

**Comment by tan-tao11** [comment]
Hi!
I met the same problem. Have U solved it?

**Comment by wangg12** [comment]
Please give more details.

**Comment by sunhan1997** [comment]
hello, many people meet this problem, can you solve it?


_Warning: unable to import datasets/nusc:
   No module named 'nuscenes'
Traceback (most recent call last):
  File "/home/sunh/6D_ws/other_code/Self6D-Diff-Renderer-master/kaolin/kaolin/datasets/__init__.py", line 11, in <module>
    from .nusc import NuscDetection
  File "/home/sunh/6D_ws/other_code/Self6D-Diff-Renderer-master/kaolin/kaolin/datasets/nusc.py", line 21, in <module>
    from nuscenes.utils.geometry_utils import transform_matrix
ModuleNotFoundError: No module named 'nuscenes'
Warning: unable to import datasets/nusc:
   None
  0%|                                                                                                                             | 0/13 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "tests/test_dib_render_LM_batch_depth.py", line 153, in <module>
    main()
  File "tests/test_dib_render_LM_batch_depth.py", line 112, in main
    models = load_objs(obj_paths, texture_paths, height=HEIGHT, width=WIDTH)
  File "/home/sunh/6D_ws/other_code/Self6D-Diff-Renderer-master/tests/../core/dr_utils/dr_utils.py", line 42, in load_objs
    vertices = mesh.vertices[:, :3]  # x,y,z
IndexError: too many indices for tensor of dimension 1_
